### ISSUE TITLE
Using with Vue-CLI 4 produces no results

### ISSUE THREAD

**Issue by AtlantaJones** [cascornelissen/svg-spritemap-webpack-plugin#110]
Been using this plugin for a while now on a few sites and it's always worked great. Up to now I've been using it in conjunction with Laravel Mix for webpack management. Recently we did a refactor on a site in-progress to use Vue-CLI (4.2.2), and now there seems to be no output whatsoever. The svg sprite isn't created and there are no errors to indicate what's happening. Here's the webpack config in `vue.config.js` that's always worked with Laravel Mix:

```js
module.exports = {
  configureWebpack: {
    plugins: [
      new SVGSpritemapPlugin("src/assets/images/svg/*.svg", {
        output: {
          filename: "../src/assets/fonts/icons.svg",
          svg4everybody: false,
          svgo: {
            removeTitle: true,
            removeStyleElement: true,
            cleanupNumericValue: true
          },
          chunk: {
            keep: true
          }
        },
        sprite: {
          prefix: false
        }
      })
    ]
  }
};
```
As for versions:
* Vue: 2.6.11
* Vue-cli: 4.2.2
* svg-spritemap-webpack-plugin: 3.5.4

Again, things were working great until switching to Vue-cli. No matter what I do, no svg file is output, and there are no errors. Hoping someone might have some ideas. Thanks!

**Comment by cascornelissen** [comment]
Since I haven't used Vue much yet, it'd help a lot if you could set up a minimal repository to reproduce the issue so I can debug the issue you're seeing using that. There's also #85 that's using Vue CLI as well (the initial issue is unrelated but it might give some pointers).

Also, it might be easier/better to inline the SVGs directly in the JS application when you're using something like Vue/React/Angular. For example, React has a few packages such as [`svg-inline-react`](https://github.com/sairion/svg-inline-react) that can support dynamic `import()`s to ensure only the SVGs loaded in the current view are downloaded.

**Comment by AtlantaJones** [comment]
Thanks! I've seen that other issue and unfortunately don't think it's related. I'm going to look into an inlining approach as you suggested with something like [this](https://www.npmjs.com/package/vue-svg-inline-loader). Would prefer to keep using yours, so maybe I can still work it out.

**Comment by drewrawitz** [comment]
Hey @AtlantaJones, I'm in a very similar boat. I'm actually switching _from_ `vue-svg-inline-loader` to something like this for performance reasons, as we are dealing with hundreds of SVGs.  

The only way I can get the sprite generation to work is by running a full `vue-cli-service build`.  Unfortunately, I can't get it to reload when my `vue-cli-service serve` is running.  I'd love to hear if you've made any progress on this.  I'll also report any of my findings.

**Comment by cascornelissen** [comment]
@drewrawitz, FYI; the offer still stands regarding the minimal repository for me to try and reproduce and maybe fix it.

**Comment by drewrawitz** [comment]
@cascornelissen Thank you!  So here's the repo I just created: https://github.com/drewrawitz/vue-svg-spritemap-test

I added two icons to the `src/assets/icons/` folder, and the sprite is getting generated here: `public/icon-sprite.svg` which works great when I run `yarn build`. 

The sprite does not get regenerated when my watcher is running, and you can test that by running `yarn serve` and then dropping a new icon into the `src/assets/icons` folder.  I added a new icon (`bike.svg`) in the assets folder so you have an icon to test with.

**Comment by cascornelissen** [comment]
@drewrawitz, awesome, thanks for the quick reply and repo, I'll look into it as soon as I find some spare time ✌️

**Comment by cascornelissen** [comment]
Alright, thanks once more for the repository, it really helped. Unfortunately (or fortunately for me) it doesn't seem to be a problem with the plugin. The changes are applied when running in watch mode, I checked this by logging the output of the following line and the updated spritemap gets added to the Webpack compilation assets without any problems. So the last step the plugin does is completed correctly.

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/214fd7b5d1b42b463fba42eedaf34f53de768b39/lib/index.js#L243

The problem seems to lie in something `vue-cli-service` does as far as I can see, it looks like the default configuration does not always write the files to disk. I checked this in the simple example in this repository with just Webpack and it does actually write the files to disk in watch mode there.

It also does not seem to be caused by the default SVG loader, which can be disabled by adding the following snippet in the `vue.config.js`.

```
chainWebpack: (config) => {
    config.module.rules.delete('svg')
}
```

What does "work" is adding the following snippet to `vue.config.js` to force the dev-server to write the files to disk on every build but this causes an infinite loop of rebuilding on my end, (probably) because some file that gets updated also triggers a rebuild for some reason.

```
devServer: {
    writeToDisk: true
}
```

Since this is getting into the Vue territory I'm stopping right here 😅 Maybe some of these tickets can give some more insights.

**Comment by drewrawitz** [comment]
@cascornelissen Thanks so much for spending some time on it! You helped point me in the right direction 😄 

I was able to get it to work by adding the following to my `vue.config.js` file under the `configureWebpack` object:

```
devServer: {
  writeToDisk: (filePath) => {
    return /icon-sprite.svg$/.test(filePath);
  },
  watchOptions: {
    ignored: [/node_modules/, /public\/icon-sprite.svg/],
  }
},
```

Vue is configured to watch the `public` folder, so this will fix the infinite loop issue.  When you first run `yarn serve` it loops like three times for some reason, but then it stops and starts to successfully work!

Hopefully, this will help someone else.  Thanks again!

**Comment by cascornelissen** [comment]
Awesome, thanks for sharing the final pieces! Now I have something to point others to when they run into similar problems 🥳

**Comment by AtlantaJones** [comment]
@drewrawitz Hey sorry for my tardiness. No, we eventually realized that new svgs were getting added to the sprite only on "build", so just kind of chalked it up to a minor inconvenience. After all, new icons aren't added often. Just have to document what's needed. 

Based on the current suggestions, definitely going to try them out and see if it also works for us. Thanks to you and @cascornelissen !!
