### ISSUE TITLE
svg4everybody not added if entry is .ts file

### ISSUE THREAD

**Issue by kareljan** [cascornelissen/svg-spritemap-webpack-plugin#140]
svg4everybody seems not to be added if your entry is a typescript file.
svg4everybody should be added to the .js output no?
Or am I missing something?

**Comment by cascornelissen** [comment]
It should at least at the file but I'm not sure what happens when the TS compiler parses it. I'm gonna need a bit more information (that's why there's a template when you create an issue). Feel free to look into it yourself and submit a PR or if you're able to set up a small repository with the required setup (Webpack, TS, this plugin) I'll have a look into what's really happening internally.
