### ISSUE TITLE
Added color to mixin & sprite (support for variables in styles)

### ISSUE THREAD

**Issue by TillmannD** [cascornelissen/svg-spritemap-webpack-plugin#31]
Hey,
first of all thanks for the great plugin!

I missed the color prop in the mixin, so I added the fill prop in the formatter files & icon.scss. Are there any plans to integrate the color, size prop to the scss/less in the future? 

Thats what I've done, it works perfectly for me:

scss-formatter.js:
`svg.setAttribute('fill', '%fill%');`

styles.scss:
```
@mixin sprite($name, $fill: #000) {
$sprite: str-replace(map-get($sprites, $name),'%25fill%25',$fill);
background: url($sprite) center no-repeat;
}
@function str-replace($string, $search, $replace: '') {
    $index: str-index($string, $search);
    @if $index {
      @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
    }
    @return $string;
}
```
I only changed the scss cause I only use scss in my proj. Maybe I will integrate the size in the sprite mixin as well.

BR
Tillmann

**Comment by cascornelissen** [comment]
Funny that you mention this, I'm currently in the process of adding basic variable support for SCSS. Thing is that there are quite a [few more attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) for SVG and people might want to use different variables for different sprites so the setup you're suggesting would mean a lot of work.

That's why I'm implementing a different approach and I'm aiming to release this feature in the next few weeks, progress is visible in the [`vars`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/vars) branch which includes [a document outlining the feature](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/vars/docs/variables.md).

Only problem I'm having at the moment is Less, I'm not a Less user myself so I don't know what the best setup for the variables in Less would be (and if there is any since it doesn't support maps/lists without a [plugin](https://www.npmjs.com/package/less-plugin-lists)) so the first release of this feature will probably only support Sass.

I'll leave this issue open until a release containing this new feature has been published.

**Comment by cascornelissen** [comment]
Hey @TillmannD, if you want (and have the time) you can check out the progress by installing the plugin from the [`vars`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/tree/vars) branch:

```
npm install --save-dev cascornelissen/svg-spritemap-webpack-plugin#vars
```

The feature feels complete to me, the documentation has been updated and I've written some basic tests. I'll be testing it on some projects myself in the next week or so and will release it when I'm sure everything works correctly.

If you (or anyone else) has feedback on this feature I'd be glad to receive it in this thread ❤️

**Comment by TillmannD** [comment]
Hey @cascornelissen 
thanks! I will take a look at it. But for now it looks very nice. :))))

**Comment by TillmannD** [comment]
Hey @cascornelissen 
It works really perfect. Very nice!

When will you merge it & release it?

**Comment by cascornelissen** [comment]
@TillmannD, great to hear! I'm hoping to test it some more this evening and will release a version containing this feature this weekend if I can find the time.

**Comment by cascornelissen** [comment]
@TillmannD, I found some issues that I'd like to get resolved before releasing the feature. Will keep you (and anyone else watching is issue) posted!

**Comment by cascornelissen** [comment]
Version [`2.6.0`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/releases/tag/v2.6.0) has just been released and published to [npm](https://www.npmjs.com/package/svg-spritemap-webpack-plugin/v/2.6.0) containing this feature, documentation can still be found [here](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/v2.6.0/docs/variables.md). 🚀
