### ISSUE TITLE
SCSS: Namespace prefix xlink for href on use is not defined

### ISSUE THREAD

**Issue by tungquach** [cascornelissen/svg-spritemap-webpack-plugin#40]
When I include svg in scss file, svg image can not display due to missing `xmlns:xlink="http://www.w3.org/1999/xlink"`

I've already created PR
https://github.com/cascornelissen/svg-spritemap-webpack-plugin/pull/38
https://github.com/cascornelissen/svg-spritemap-webpack-plugin/pull/39

**Comment by cascornelissen** [comment]
Can you provide the source SVG (sprite) and where exactly are you seeing this error? In a browser/terminal or somewhere else?

Thanks for the PRs!

**Comment by tungquach** [comment]
@cascornelissen 
I faced error on browser
https://drive.google.com/a/brodev.com/file/d/1x7-DisstrmNNrWia5GjruCuDhPln94dz/view?usp=drivesdk
https://drive.google.com/a/brodev.com/file/d/1TN-X8EepfDxBIkHbRwptQS1rOBmTJZ9T/view?usp=drivesdk

Here are some resources:
_sprite.scss:
`$sprites: (
    'dashboard': "data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e %3cdefs%3e %3cpath id='a' d='M2 0c7.72 0 14 6.28 14 14.001v1h-4v-2h1.949a11.939 11.939 0 0 0-2.795-6.741L9.778 7.636 8.364 6.222l1.377-1.376A11.942 11.942 0 0 0 3 2.051V4H1V0h1zm6.414 9L5.7 11.714c.187.391.3.824.3 1.286a3 3 0 1 1-3-3c.462 0 .895.113 1.286.3L7 7.586 8.414 9z'/%3e %3c/defs%3e %3cg fill='none' fill-rule='evenodd'%3e %3cmask id='b' fill='white'%3e %3cuse xmlns:xlink='http://www.w3.org/1999/xlink' xlink:href='%23a'/%3e %3c/mask%3e %3cuse fill='white' fill-rule='nonzero' xlink:href='%23a'/%3e %3cg fill='white' mask='url(%23b)'%3e %3cpath d='M0 0h16v16H0z'/%3e %3c/g%3e %3c/g%3e %3c/svg%3e"
);

@mixin sprite($name) {
    $sprite: map-get($sprites, $name);
    background: url($sprite) center no-repeat;
}
`
dashboard.svg:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16" viewBox="0 0 16 16">
    <defs>
        <path id="a" d="M2 0c7.72 0 14 6.28 14 14.001v1h-4v-2h1.949a11.939 11.939 0 0 0-2.795-6.741L9.778 7.636 8.364 6.222l1.377-1.376A11.942 11.942 0 0 0 3 2.051V4H1V0h1zm6.414 9L5.7 11.714c.187.391.3.824.3 1.286a3 3 0 1 1-3-3c.462 0 .895.113 1.286.3L7 7.586 8.414 9z"/>
    </defs>
    <g fill="none" fill-rule="evenodd">
        <mask id="b" fill="#fff">
            <use xlink:href="#a"/>
        </mask>
        <use fill="#FFF" fill-rule="nonzero" xlink:href="#a"/>
        <g fill="#FFF" mask="url(#b)">
            <path d="M0 0h16v16H0z"/>
        </g>
    </g>
</svg>`

**Comment by cascornelissen** [comment]
Thanks for the details @tungquach, as I thought this isn't necessarily a problem with the plugin (well it is, but not the problem you're trying to fix in PR #38 and #39).

**Issue**
You're running into this issue because the `dashboard.svg` sprite you've provided contains a `xlink:href` attribute which comes with a `xmlns:xlink` attribute on the root `svg` element. Your solution would add the `xmlns:xlink` attribute to all sprites in the `styles` output but it's not needed on sprites which do not use any attributes with the `xlink` namespace.

**Solution**
The correct solution to this problem would be to preserve all `xmlns:*` attributes from the root element. The reason I haven't implemented that is because in my own research and tests it's not required, the SVGs render correctly.

[This answer on StackOverflow](https://stackoverflow.com/a/18468348/1358948) explains it pretty well:

> If you embed your SVG inline in a HTML page and serve that page as text/html then xmlns attributes are not required. Embedding SVG inline in HTML documents is a fairly recent innovation that came along as part of HTML5.
>
> If however you serve your page as image/svg+xml or application/xhtml+xml or any other MIME type that causes the user agent to use an XML parser then the xmlns attributes are required. This was the only way to do things until recently so there is a lot of content served like this.

My guess is your SVG is working correctly in the project (assuming you're using the HTML5 doctype) and you're seeing the error when opening the optimized URL directly in your browser. That's a result of the browser guessing the provided string is XML which will use the browser XML parser.

**Opinion**
Since it's an optimized spritemap (or seperates sprites in this case) there's really no need for it to display correctly on itself. My personal preference would be to not add the additional `xmlns` attributes as they increase the size of the output and don't do anything other than instructing XML parsers (which should never receive such sprites) on the usage of namespaces.

**Comment by tungquach** [comment]
Thank you for explain, but can we keep `xmlns:xlink` if it exists and svg source contains `xlink:href`?
Otherwise svg background image can not display in web app (at least in my case). Sorry if I misunderstood something.

**Comment by cascornelissen** [comment]
It would be possible to keep the `xmlns:xlink` namespace when it exists in the source but it shouldn't be required. Do you have a basic example which I can use to reproduce the error?

**Comment by tungquach** [comment]
[svg_sprites.zip](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/files/2087721/svg_sprites.zip)
Here is it, Cas!

**Comment by cascornelissen** [comment]
Hi @tungquach, sorry for taking so long. I inspected your example but the `dashboard.svg` *does* have the correct `xmlns:xlink` namespace and still doesn't show so I'm either misunderstanding what you mean or you're running into another problem than the one you're describing.

Let me know!
