### ISSUE TITLE
Add display=none to main SVG sprite output

### ISSUE THREAD

**Issue by a-am** [cascornelissen/svg-spritemap-webpack-plugin#51]
Is there currently a way to automatically add `display='none'` to the svg sprite?  Otherwise it needs to be added manually.

**Comment by cascornelissen** [comment]
Hi @a-am, what would be the use case for this feature? 

There currently isn't anything that could do this but if there is an interesting use case for such a thing I'm willing to accept a PR/implement it.

**Comment by a-am** [comment]
@cascornelissen to use the sprite we are including it in the html, however the sprite itself needs to be hidden so it doesn't display all svgs in the document.

**Comment by cascornelissen** [comment]
Interesting, I feel like that should be done in the project itself (through CSS), as it's quite trivial to add those 3 lines of code, instead of through the plug-in. The generated SVG should probably never have `display: none;` or any other specific styling as it's always possible it will also be included from the external URL as well. 

Everyone is welcome to argue with me on this of course ✌️

**Comment by a-am** [comment]
You may be right.  How do you commonly implement.  Included it at the end of the document and then do. 
```
svg:last-child {
 display: none;
}
```

**Comment by cascornelissen** [comment]
I would probably wrap it in a `div` or something with a specific class and target that div as I've ran into issues with directly styling SVGs in older version of Internet Explorer myself.
