### ISSUE TITLE
Google Play badge doesn't work with this plugin

### ISSUE THREAD

**Issue by DreadBoy** [cascornelissen/svg-spritemap-webpack-plugin#68]
Repro case: https://github.com/DreadBoy/svg-spritemap-webpack-plugin/commit/f8f0a1161534c709337a1b3fb01414884dd27415

Badge was downloaded from https://commons.wikimedia.org/wiki/File:Get_it_on_Google_play.svg

Repro steps:
1. pull my fork and build simple example
2. run `http-server` (or anything similar) in example's root
3. open index.html

I don't see gradients in Play's logo because they were removed from spritemap. I tried turning off Svg4Everybody and SVGO but it didn't help. Do you have any idea why they are being removed. SVG renders fine if I open it as is.

**Comment by cascornelissen** [comment]
Just checked your repro case, the gradients do end up in the spritemap so that's not where it's going wrong... The problem is that the entire `<defs>` element (which holds the `<linearGradient>` definitions) gets stripped when loading the SVG via a `<use>` element, which matches with [the specification](https://www.w3.org/TR/SVG11/struct.html#SymbolElement).

A solution would be to load the `svg4everybody` helper like so (which fetches the entire SVG and injects it into the HTML):

```es6
new SVGSpritemapPlugin('src/**/*.svg', {
    output: {
        svg4everybody: {
            polyfill: true
        }
    }
})
``` 

Another option would be to include the entire SVG at the top of your file and use the `<use>` tag with a local `href` value (without the path):

```xml
<use href="#sprite-google-play"/>
```
