### ISSUE TITLE
Proposal: Write to disk .svg sprite

### ISSUE THREAD

**Issue by litinskii** [cascornelissen/svg-spritemap-webpack-plugin#76]
Add some kind of options like `alwaysWriteToDisk` to generated output of svg-sprite to disk. This is very useful if you want to pick up the output with another middleware.

**Comment by cascornelissen** [comment]
Sounds like a valid use-case to me. I currently don't have much time to implement new features but anyone is free to submit a PR of course. I'd prefer the option to be available under `output.alwaysWriteToDisk` then.

I do have a couple of questions, though:

1. Where would the file be written to? Will this always be the webpack output directory or should it be possible to specify a path (and in that case, should it then be outputted twice)?
1. The SVG can only be generated during the [`make` compiler hook](https://webpack.js.org/api/compiler-hooks/#make) because of dependencies so I'm not sure if this is really helpful in your case? If not then the [`needsAdditionalPass` compilation hook](https://webpack.js.org/api/compilation-hooks/#needadditionalpass) might be useful to trigger a recompile when the spritemap gets updated.

For now, as it's unclear to me what you're trying to do you might also want to take a look at a plugin like the [event-hooks-webpack-plugin](https://www.npmjs.com/package/event-hooks-webpack-plugin) in combination with the [`afterEmit` compiler hook](https://webpack.js.org/api/compiler-hooks/#afteremit).

**Comment by litinskii** [comment]
I'm not sure, but it could be like `html-webpack-harddisk-plugin`, that work together  `html-webpack-plugin` (like an extension plugin for the webpack plugin html-webpack-plugin), so in this case it will be `svg-spritemap-webpack-harddisk-plugin` or something like this, where we could specify options like `outputPath`

about 1, I think it should be work like this,  `outputPath || compilation.compiler.outputPath` grab `outputPath` from options that user provide or use standard (not sure is this valid) 
about 2, sorry I'm not so good in knowledge how webpack work, so no answer about that (

about what I'm trying to do, is that I want to pick up generated svg with other plugins (copy or process this output) for example when i'm run web-pack-dev-server

I will take a look at event-hooks-webpack-plugin, thanks )

In any case this is proposal not bug or some kind report of incorrect work, that work that you done in that plugin is super huge, thanks for that )

**Comment by cascornelissen** [comment]
Sounds clear to me, and as I said; a PR is always welcome 😄

**Comment by ahmedfaical** [comment]
+1 any news ?
