### ISSUE TITLE
SVG Attributes isn't applied when generating symbol

### ISSUE THREAD

**Issue by Fire-Proof** [cascornelissen/svg-spritemap-webpack-plugin#89]
When trying convert a simple svg with a stroke defined on the svg element, the symbol doesn't receive all attributes, eg:

**Input**:
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10" stroke="#000">
    <path d="M0 5h10"/>
</svg>
```
<details><summary>Image</summary>

![image](https://user-images.githubusercontent.com/1039554/65238611-4f9fa180-dadd-11e9-8fcd-647c1260c2c4.png)

</details>

**Output**:
```xml
<symbol id="line" viewBox="0 0 10 10">
    <path d="M0 5h10"></path>
</symbol>
```

<details><summary>Image</summary>

![image](https://user-images.githubusercontent.com/1039554/65238652-6ba34300-dadd-11e9-8d76-a88c79939d67.png)

</details>

Is this intentional? It seems like preserveAspectRatio is the only attribute that passes to the symbol element

**Comment by cascornelissen** [comment]
That's because the `stroke` attribute isn't available on the `svg` element according to the [spec](https://www.w3.org/TR/SVG2/struct.html#SVGElement) even though it might work in practice. The stroke should be on the `path` in your example.

**Comment by Fire-Proof** [comment]
Are you sure about that? It's listed under [presentation attributes](https://www.w3.org/TR/SVG2/styling.html#TermPresentationAttribute), which is available to the `svg` element, the file also validates on https://validator.w3.org

**Comment by cascornelissen** [comment]
Yeah, I'm pretty sure although I'm not 100% confident in my spec-reading abilities either 😅  

- The link you used for the presentation attributes (https://www.w3.org/TR/SVG2/styling.html#TermPresentationAttribute) shows all presentation attributes in the entire SVG spec, it's not related to the `<svg>` element specifically. If you click on the `show >>` button that's behind the *presentational attributes* section in the link I sent it shows a dash indicating that there are no presentational attributes on this element.
- The W3C validator validates XML which doesn't look at specific properties being defined in a spec. It also validates a `abc="123"` attribute for example.

**Comment by Fire-Proof** [comment]
Oh you're right, i'm a bit new to these w3 specs :man_shrugging:. However if you specify the w3-validators doctype as `svg 1.1`, it will accept my example as valid, and something like `abc="123"` as invalid

<details><summary>Valid</summary>


![image](https://user-images.githubusercontent.com/1039554/65247871-74057900-daf1-11e9-8844-e5753fe68582.png)


</details>

<details><summary>Invalid</summary>


![image](https://user-images.githubusercontent.com/1039554/65247943-a0b99080-daf1-11e9-888a-4e1df2ae2715.png)


</details>

And even if it isn't valid in the spec, it's used by some icon collections, eg:  [Feather](https://github.com/feathericons/feather/blob/master/icons/activity.svg?short_path=2eccd9c) (which is why i'm having this issue)

**Comment by cascornelissen** [comment]
Hmm, that's interesting. Since you have a pretty popular icon set as an example I guess it would be good to support this. Could you also verify it's not SVGO stripping these attributes by setting [`output.svgo`](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#outputsvgo--true) to `false`?

**Comment by Fire-Proof** [comment]
Yeah, I have tested it both with and without `output.svgo` set to `false`

**Comment by cascornelissen** [comment]
Alright, I just took a deeper dive into this and I guess we could update the logic here:

https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/f411076687636541a06b49b536550ea53c94062f/lib/generate-svg.js#L160-L166

We should accept all valid SVG attributes there instead of just `preserveAspectRatio`, using something like [`svg-element-attributes`](https://www.npmjs.com/package/svg-element-attributes) might work for that, [the list](https://github.com/wooorm/svg-element-attributes/blob/273dc1465659cb3bd726bfab880c6160d0defeac/index.json#L3537-L3632) looks complete to me.

Would you be willing to submit a PR for this?
